### ISSUE TITLE
功能建议: 增加右键主动调用插件

### ISSUE THREAD

**Issue by winezer0** [shuanx/BurpFingerPrint#4]
功能建议: 
1、增加右键主动调用插件识别响应内容

2、增加插件被动识别的功能开关

3、将识别页面 作为 前一页，配置页面作为 后一页

4、【导入】功能 目前似乎无法使用

5、【全部】按钮 目前似乎无法使用

**Comment by shuanx** [comment]
没问题，导入、充值那些功能还在写

**Comment by winezer0** [comment]
can you release
